version: "3.8"
services:
  api-db:
    image: postgres:16.2
    container_name: api-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: api-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789